/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: "us-east-1:863550e5-4e8c-4b57-9a93-7d9be6566fe8",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_5aDBU6ZMS",
  aws_user_pools_web_client_id: "6qb4nf3o763ci5ugn88iv5jd27",

  oauth: {
    domain: "us-east-15adbu6zms.auth.us-east-1.amazoncognito.com",
    scope: ["openid", "email", "profile"],
    redirectSignIn:
      "http://localhost:3000/auth/callback,https://main.dkva3zbv2kejl.amplifyapp.com/auth/callback",
    redirectSignOut:
      "http://localhost:3000/,https://main.dkva3zbv2kejl.amplifyapp.com/",
    responseType: "code",
  },

  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],

  aws_user_files_s3_bucket: "heirloom4fb45a235d9c4898b0945e36bdf4d97548b52-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;